#!/bin/bash

# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <postinst> `abort-remove'
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>
# for details, see https://www.debian.org/doc/debian-policy/ or
# the debian-policy package


after_install() {
    touch "__INSTALL_3DIGIT__"/conf/.not_configured_yet
}

after_upgrade() {
    OLD_TIMESTAMP=$1
    OLD_VERSION=$(echo "$OLD_TIMESTAMP" | grep -o '^[0-9]*\.[0-9]*\.[0-9]*')

    #
    # Remove directory with old version
    #
    NEW_VERSION=$(cat __PREFIX__/livy/livyversion)

    if [ "$OLD_VERSION" != "$NEW_VERSION" ]; then
        rm -rf "__PREFIX__/livy/livy-${OLD_VERSION}"
    fi
}


case "$1" in
    configure)
        if [ -z "$2" ] ; then
            after_install
        else
            after_upgrade "$2"
        fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
