#!/bin/bash

# summary of how this script can be called:
#        * <postrm> `remove'
#        * <postrm> `purge'
#        * <old-postrm> `upgrade' <new-version>
#        * <new-postrm> `failed-upgrade' <old-version>
#        * <new-postrm> `abort-install'
#        * <new-postrm> `abort-install' <old-version>
#        * <new-postrm> `abort-upgrade' <old-version>
#        * <disappearer's-postrm> `disappear' <overwriter>
#          <overwriter-version>
# for details, see https://www.debian.org/doc/debian-policy/ or
# the debian-policy package


after_remove() {
    if [ -f __PREFIX__/conf/conf.d/warden.livy.conf ]; then
        rm -f __PREFIX__/conf/conf.d/warden.livy.conf
    fi
}

after_purge() {
    rm -rf __PREFIX__/livy/
}


case "$1" in
    purge)
        after_remove
        after_purge
    ;;
    remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
        after_remove
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
